fail_on_violations: true

coffeescript:
  config_file: coffeescript.json

jshint:
  config_file: jshintrc
  ignore_file: .jshintignore

ruby:
  config_file: ruby.yml

scss:
  config_file: scss.yml

haml:
  config_file: haml.yml
